/*
    // cookie
        small files that generated by web servers and sends to the web browser
*/

// alert(document.cookie); // (key = value;)

// // add the cookie
// document.cookie = 'name=roshan';
// document.cookie = 'name2=radha';

/*
Session Cookies : 
    => These cookies are temporary and exist only for the duration of the user's browsing session. 
    => They are deleted when the user closes their browser.
    => They are created when neither the max-age nor the expires attribute is set in the Set-Cookie header.

Persistent Cookies:
    => These cookies remain on the user's computer for a specified period of time.
    => They are not deleted when the browser is closed.
    => They are created when either the max-age or the expires attribute is set in the Set-Cookie header.
    => max-age defines the lifespan in seconds.
    => expires defines the lifespan using a specific date and time.
*/

// set expires
document.cookie = "username=JohnDoe; expires=Fri, 19 Apr 2025 12:00:00 UTC"; // expires after date

// // set max-age
document.cookie = "username=JohnDoe; max-age=3600"; // Expires in 1 hour

document.cookie = "username=mithoon; expires=Thu, 18 Dec 2026 12:00:00 UTC; path=/ele; HttpOnly; Secure; SameSite=Strict";

// let date = new Date();
// document.cookie = `age = 23; expires = ${date}; max-age=10;`;

// // update the cookie
// document.cookie = 'name=Aakash';



// alert(document.cookie);

// let key = prompt('Enter the key'); //if enters => man;
// let value = prompt('Enter the value');

// document.cookie = `${encodeURIComponent(key)}=${encodeURIComponent(value)}`;
// console.log(document.cookie);

// // if you want to decode ...
// console.log('key ', decodeURIComponent(key));
// console.log('value ', decodeURIComponent(value));


/*
Local Storage
    - if i don't want to share cookie again and again for every request than use local storage
    - it survives all reload , restart and repaste
*/

// // how to set local storage
// localStorage.setItem('name', 'Roshan'); // setItem(key , value)
// localStorage.getItem('name') // getItem(key)

// let key = prompt('Enter the key');
// let value = prompt('Enter the value');

// localStorage.setItem(key, value);

// console.log(`your key ${key} and value is ${value}`);

// // remove key from localstorage
// if (key == 'color') {
//     localStorage.removeItem(key);
// }

// // clear the entire localstorage
// if (key == 0) {
//     localStorage.clear();
// }

// // length of localstorage
// console.log(localStorage.length);

// sessionStorage.setItem(key, value);
// sessionStorage.getItem(key);
// sessionStorage.removeItem(key);
// sessionStorage.clear();

// storage event => update in one tab and changes notified in another tab of the same page

// The window.onstorage event is only triggered when a change to localStorage or sessionStorage is made
//  in another tab or window.

// window.onstorage = (event_obj) => {
//     alert('change');
//     console.log(event_obj);
// }

/*
localstorage : can survive refresh/reload , repaste and closing browser window/tab
sessionstorage : can survive refresh/ reload , not a closing broser window/tab and repaste
cookie : can survive survive refresh , reload 
    session cookie : which don't have expires
    persistent cookie : which has expires 
*/
