/*
    // cookie
        small files that generated by web servers and sends to the web browser
*/

// alert(document.cookie); // (key = value;)

// // add the cookie
// document.cookie = 'name=roshan';
// document.cookie = 'name2=radha';
// // update the cookie
// document.cookie = 'name=Aakash';

// alert(document.cookie);

// let key = prompt('Enter the key'); //if enters => man;
// let value = prompt('Enter the value');

// document.cookie = `${encodeURIComponent(key)}=${encodeURIComponent(value)}`;
// console.log(document.cookie);

// // if you want to decode ...
// console.log('key ', decodeURIComponent(key));
// console.log('value ', decodeURIComponent(value));


/*
Local Storage
    - if i don't want to share cookie again and again for every request than use local storage
    - it survives all reload , restart and repaste
*/

// // how to set local storage
// localStorage.setItem('name', 'Roshan'); // setItem(key , value)
// localStorage.getItem('name') // getItem(key)

// let key = prompt('Enter the key');
// let value = prompt('Enter the value');

// localStorage.setItem(key, value);

// console.log(`your key ${key} and value is ${value}`);

// // remove key from localstorage
// if (key == 'color') {
//     localStorage.removeItem(key);
// }

// // clear the entire localstorage
// if (key == 0) {
//     localStorage.clear();
// }

// // length of localstorage
// console.log(localStorage.length);

// sessionStorage.setItem(key, value);
// sessionStorage.getItem(key);
// sessionStorage.removeItem(key);
// sessionStorage.clear(); 

// storage event => update in one tab and changes notified in another tab of the same page

window.onstorage = (event_obj) => {
    alert('change');
    console.log(event_obj);
}